c_compiler:                # [win]
  - vs2019                 # [win]
  - vs2017                 # [win]
cxx_compiler:              # [win]
  - vs2019                 # [win]
  - vs2017                 # [win]
