{% set test_cmake_args = "-D \"CMAKE_SYSTEM_PREFIX_PATH:FILEPATH=${PREFIX}\" ./Examples" %}  # [not win]
{% set test_cmake_args = "-D \"CMAKE_SYSTEM_PREFIX_PATH:FILEPATH=%PREFIX%\" ./Examples" %}  # [win]
{% set name = "libsimpleitk" %}
{% set version = "2.4.0" %}
{% set sha256 = "7498c1bd3ae8218027c17bcefd2346b16eda6f2a009c0b9f344bd163c4715870" %}


{% set test_cmake_args = "-D \"CMAKE_SYSTEM_PREFIX_PATH:FILEPATH=${PREFIX}\" ./Examples" %}  # [not win]
{% set test_cmake_args = "-D \"CMAKE_SYSTEM_PREFIX_PATH:FILEPATH=%PREFIX%\" ./Examples" %}  # [win]

package:
  name: {{ name }}
  version: {{ version }}

source:
   git_url: https://github.com/SimpleITK/SimpleITK.git
   git_rev: v{{ version }}

build:
  number: 1

requirements:
  build:
    - cmake   >=3.26
    - ninja
    - lua     5.4.*
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}

  host:
    - libitk-devel 5.4.*


test:
  requires:
    - cmake
    - ninja
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - libitk-devel
  source_files:
    - Examples
  commands:
    - test -d $PREFIX/include/SimpleITK*                                          # [not win]
    - if not exist %LIBRARY_INC%\\SimpleITK* exit 1                               # [win]
    - cmake -G Ninja -D "CMAKE_SYSTEM_PREFIX_PATH:FILEPATH=${PREFIX}" ./Examples  # [not win]
    - cmake -G Ninja -D "CMAKE_SYSTEM_PREFIX_PATH:FILEPATH=%PREFIX%" -D CMAKE_BUILD_TYPE:STRING=RELEASE ./Examples     # [win]
    - cmake --build . --config Release

about:
  home: http://www.simpleitk.org
  license: Apache-2.0
  license_file: LICENSE
  summary: Development headers and libraries for SimpleITK a simplified interface to the Insight Toolkit.

extra:
  recipe-maintainers:
    - blowekamp
    - zivy
