{% set test_cmake_args = "-D \"CMAKE_SYSTEM_PREFIX_PATH:FILEPATH=${PREFIX}\" ./Examples" %}  # [not win]
{% set test_cmake_args = "-D \"CMAKE_SYSTEM_PREFIX_PATH:FILEPATH=%PREFIX%\" ./Examples" %}  # [win]
{% set name = "libsimpleitk" %}
{% set version = "2.2.1" %}
{% set sha256 = "304e2dc676e456542bff5e466e2184a7aaa6e01e4c190a8c070e59c520c6b425" %}


{% set test_cmake_args = "-D \"CMAKE_SYSTEM_PREFIX_PATH:FILEPATH=${PREFIX}\" ./Examples" %}  # [not win]
{% set test_cmake_args = "-D \"CMAKE_SYSTEM_PREFIX_PATH:FILEPATH=%PREFIX%\" ./Examples" %}  # [win]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SimpleITK/SimpleITK/releases/download/v{{ version }}/SimpleITK-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - cmake   >=3.15
    - ninja
    - lua     5.3.*
    - swig    4.0.*
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - libitk-devel  5.3.*

  run:
    - vs2015_runtime  # [win]
    - {{ pin_compatible('libitk-devel', exact=True) }}

test:
  requires:
    - cmake
    - ninja
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
  source_files:
    - Examples
  commands:
    - test -d $PREFIX/include/SimpleITK*                                          # [not win]
    - if not exist %LIBRARY_INC%\\SimpleITK* exit 1                               # [win]
    - cmake -G Ninja -D "CMAKE_SYSTEM_PREFIX_PATH:FILEPATH=${PREFIX}" ./Examples  # [not win]
    - cmake --build . --config Release                                            # [not win]

about:
  home: http://www.simpleitk.org
  license: Apache-2.0
  license_file: LICENSE
  summary: Development headers and libraries for SimpleITK a simplified interface to the Insight Toolkit.

extra:
  recipe-maintainers:
    - blowekamp
    - zivy
