{% set version = "2.4.1" %}

package:
  name: libsimpleitk
  version: {{ version }}

source:
  url: https://github.com/SimpleITK/SimpleITK/releases/download/v{{ version }}/SimpleITK-{{ version }}.tar.gz
  sha256: 23aaf20e88a5b1152b41dba574416c79b1d35b73c7f027eacad5e4d13af020bd

build:
  number: 0

requirements:
  build:
    - cmake   >=3.16.3
    - ninja
    - lua     5.4.*
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}

  host:
    - libitk-devel  5.4.*

test:
  requires:
    - cmake
    - ninja
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - libitk-devel
  source_files:
    - Examples
  commands:
    - test -d $PREFIX/include/SimpleITK*                                          # [not win]
    - if not exist %LIBRARY_INC%\\SimpleITK* exit 1                               # [win]
    - cmake -G Ninja -D "CMAKE_SYSTEM_PREFIX_PATH:FILEPATH=${PREFIX}" ./Examples  # [not win]
    - cmake -G Ninja -D "CMAKE_SYSTEM_PREFIX_PATH:FILEPATH=%PREFIX%" -D CMAKE_BUILD_TYPE:STRING=RELEASE ./Examples     # [win]
    - cmake --build . --config Release

about:
  home: http://www.simpleitk.org
  license: Apache-2.0
  license_file: LICENSE
  summary: Development headers and libraries for SimpleITK a simplified interface to the Insight Toolkit.

extra:
  recipe-maintainers:
    - blowekamp
    - zivy
